"""5th try

Revision ID: 511995db6003
Revises: 4b791184bc38
Create Date: 2025-03-25 15:57:43.354254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511995db6003'
down_revision = '4b791184bc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
