"""relationships

Revision ID: 8406f6ab996d
Revises: cb3a94c250f0
Create Date: 2025-03-27 10:19:52.914110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8406f6ab996d'
down_revision = 'cb3a94c250f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('book_id', type_='foreignkey')
        batch_op.drop_constraint('lender_id', type_='foreignkey')
        batch_op.drop_constraint('borrower_id', type_='foreignkey')
        batch_op.create_foreign_key("book_id", 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
        batch_op.create_foreign_key("borrower_id", 'users', ['borrower_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key("lender_id", 'users', ['lender_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('book_id', type_='foreignkey')
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.create_foreign_key("book_id", 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
        batch_op.create_foreign_key("user_id", 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_constraint('book_id', type_='foreignkey')
        batch_op.create_foreign_key("book_id", 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
        batch_op.create_foreign_key("user_id", 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_id', 'books', ['book_id'], ['book_id'])
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key('book_id', 'books', ['book_id'], ['book_id'])

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('borrower_id', 'users', ['borrower_id'], ['user_id'])
        batch_op.create_foreign_key('lender_id', 'users', ['lender_id'], ['user_id'])
        batch_op.create_foreign_key('book_id', 'books', ['book_id'], ['book_id'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
