"""no ondelete cascade

Revision ID: b996065c6b8b
Revises: 511995db6003
Create Date: 2025-03-25 16:21:31.549485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b996065c6b8b'
down_revision = '511995db6003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('borrower_id', type_='foreignkey')
        batch_op.drop_constraint('lender_id', type_='foreignkey')
        batch_op.drop_constraint('book_id', type_='foreignkey')
        batch_op.create_foreign_key("lender_id", 'users', ['lender_id'], ['user_id'])
        batch_op.create_foreign_key("book_id", 'books', ['book_id'], ['book_id'])
        batch_op.create_foreign_key("borrower_id", 'users', ['borrower_id'], ['user_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('book_id', type_='foreignkey')
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.create_foreign_key("book_id", 'books', ['book_id'], ['book_id'])
        batch_op.create_foreign_key("user_id", 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('book_id', type_='foreignkey')
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.create_foreign_key("book_id", 'books', ['book_id'], ['book_id'])
        batch_op.create_foreign_key("user_id", 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('book_id', 'books', ['book_id'], ['book_id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('book_id', 'books', ['book_id'], ['book_id'], ondelete='CASCADE')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_id', 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('lender_id', 'users', ['lender_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('borrower_id', 'users', ['borrower_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
